name: Demo CI/CD

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '11.0.x'
        java-package: jdk
        architecture: x64
    - name: build
      env: 
        DOCKER_HUB: ${{ secrets.DOCKER_HUB}}
        DOCKER_HUB_KEY: ${{ secrets.DOCKER_HUB_KEY}} 
      run: |
        echo 'Building the project...'
        ./mvnw clean install
        echo 'Login into Dockerhub...'
        docker login -u $DOCKER_HUB -p $DOCKER_HUB_KEY
        echo 'Running the build...'
        docker build . -t fertorija/fertorija:demo-latest
        echo 'Pushing image...'
        docker push fertorija/fertorija:demo-latest
        echo 'Done'
        
